//  {
//         "links": {
//             "articleList": [
//                 {
//                     "adminAdd": false,
//                     "apkLink": "",
//                     "audit": 1,
//                     "author": "鸿洋",
//                     "canEdit": false,
//                     "chapterId": 651,
//                     "chapterName": "鸿蒙开发常用链接",
//                     "collect": false,
//                     "courseId": 13,
//                     "desc": "在线查询 Javascript相关 API，且支持在线运行，当部分鸿蒙 API 不支持时，可以选择编写 TS 代码实现。",
//                     "descMd": "",
//                     "envelopePic": "",
//                     "fresh": false,
//                     "host": "",
//                     "id": 28026,
//                     "isAdminAdd": false,
//                     "link": "https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects",
//                     "niceDate": "2024-02-24 12:04",
//                     "niceShareDate": "2024-02-24 12:04",
//                     "origin": "",
//                     "prefix": "",
//                     "projectLink": "",
//                     "publishTime": 1708747448000,
//                     "realSuperChapterId": 648,
//                     "selfVisible": 0,
//                     "shareDate": 1708747448000,
//                     "shareUser": "",
//                     "superChapterId": 649,
//                     "superChapterName": "鸿蒙Tab",
//                     "tags": [],
//                     "title": "在线TS API文档",
//                     "type": 0,
//                     "userId": -1,
//                     "visible": 1,
//                     "zan": 0
//                 },
//                 {
//                     "adminAdd": false,
//                     "apkLink": "",
//                     "audit": 1,
//                     "author": "鸿洋",
//                     "canEdit": false,
//                     "chapterId": 651,
//                     "chapterName": "鸿蒙开发常用链接",
//                     "collect": false,
//                     "courseId": 13,
//                     "desc": "在这里找到所有的可以直接查找到的鸿蒙仓库，鸿蒙官方仓库地址。",
//                     "descMd": "",
//                     "envelopePic": "",
//                     "fresh": false,
//                     "host": "",
//                     "id": 28027,
//                     "isAdminAdd": false,
//                     "link": "https://ohpm.openharmony.cn/#/cn/home",
//                     "niceDate": "2024-02-24 12:04",
//                     "niceShareDate": "2024-02-24 12:04",
//                     "origin": "",
//                     "prefix": "",
//                     "projectLink": "",
//                     "publishTime": 1708747489000,
//                     "realSuperChapterId": 648,
//                     "selfVisible": 0,
//                     "shareDate": 1708747489000,
//                     "shareUser": "",
//                     "superChapterId": 649,
//                     "superChapterName": "鸿蒙Tab",
//                     "tags": [],
//                     "title": "OpenHarmony三方库中心仓",
//                     "type": 0,
//                     "userId": -1,
//                     "visible": 1,
//                     "zan": 0
//                 },
//                 {
//                     "adminAdd": false,
//                     "apkLink": "",
//                     "audit": 1,
//                     "author": "鸿洋",
//                     "canEdit": false,
//                     "chapterId": 651,
//                     "chapterName": "鸿蒙开发常用链接",
//                     "collect": false,
//                     "courseId": 13,
//                     "desc": "面向HarmonyOS应用及元服务开发者提供的集成开发环境(IDE)，助力高效开发。\n",
//                     "descMd": "",
//                     "envelopePic": "",
//                     "fresh": false,
//                     "host": "",
//                     "id": 28062,
//                     "isAdminAdd": false,
//                     "link": "https://developer.huawei.com/consumer/cn/deveco-studio/",
//                     "niceDate": "2024-02-25 15:56",
//                     "niceShareDate": "2024-02-25 15:56",
//                     "origin": "",
//                     "prefix": "",
//                     "projectLink": "",
//                     "publishTime": 1708847817000,
//                     "realSuperChapterId": 648,
//                     "selfVisible": 0,
//                     "shareDate": 1708847817000,
//                     "shareUser": "",
//                     "superChapterId": 649,
//                     "superChapterName": "鸿蒙Tab",
//                     "tags": [],
//                     "title": "官方IDE下载：HUAWEI DevEco Studio",
//                     "type": 0,
//                     "userId": -1,
//                     "visible": 0,
//                     "zan": 0
//                 },
//                 {
//                     "adminAdd": false,
//                     "apkLink": "",
//                     "audit": 1,
//                     "author": "鸿洋",
//                     "canEdit": false,
//                     "chapterId": 651,
//                     "chapterName": "鸿蒙开发常用链接",
//                     "collect": false,
//                     "courseId": 13,
//                     "desc": "本文档适用于HarmonyOS应用开发的初学者。",
//                     "descMd": "",
//                     "envelopePic": "",
//                     "fresh": false,
//                     "host": "",
//                     "id": 28063,
//                     "isAdminAdd": false,
//                     "link": "https://developer.huawei.com/consumer/cn/doc/harmonyos-guides-V2/start-overview-0000001478061421-V2\n",
//                     "niceDate": "2024-02-25 15:57",
//                     "niceShareDate": "2024-02-25 15:57",
//                     "origin": "",
//                     "prefix": "",
//                     "projectLink": "",
//                     "publishTime": 1708847864000,
//                     "realSuperChapterId": 648,
//                     "selfVisible": 0,
//                     "shareDate": 1708847864000,
//                     "shareUser": "",
//                     "superChapterId": 649,
//                     "superChapterName": "鸿蒙Tab",
//                     "tags": [],
//                     "title": "官方开发指南：HarmonyOS开发者文档",
//                     "type": 0,
//                     "userId": -1,
//                     "visible": 0,
//                     "zan": 0
//                 },
//                 {
//                     "adminAdd": false,
//                     "apkLink": "",
//                     "audit": 1,
//                     "author": "鸿洋",
//                     "canEdit": false,
//                     "chapterId": 651,
//                     "chapterName": "鸿蒙开发常用链接",
//                     "collect": false,
//                     "courseId": 13,
//                     "desc": "鸿蒙官方ArkTS所有接口参考。",
//                     "descMd": "",
//                     "envelopePic": "",
//                     "fresh": false,
//                     "host": "",
//                     "id": 28064,
//                     "isAdminAdd": false,
//                     "link": "https://developer.huawei.com/consumer/cn/doc/harmonyos-references-V2/3a5_u53e3_u53c2_u8003_uff08arkts_u53cajs-api_uff09-0000001478341265-V2\n",
//                     "niceDate": "2024-02-25 15:57",
//                     "niceShareDate": "2024-02-25 15:57",
//                     "origin": "",
//                     "prefix": "",
//                     "projectLink": "",
//                     "publishTime": 1708847878000,
//                     "realSuperChapterId": 648,
//                     "selfVisible": 0,
//                     "shareDate": 1708847878000,
//                     "shareUser": "",
//                     "superChapterId": 649,
//                     "superChapterName": "鸿蒙Tab",
//                     "tags": [],
//                     "title": "官方API参考：ArkTS接口参考",
//                     "type": 0,
//                     "userId": -1,
//                     "visible": 0,
//                     "zan": 0
//                 },
//                 {
//                     "adminAdd": false,
//                     "apkLink": "",
//                     "audit": 1,
//                     "author": "鸿洋",
//                     "canEdit": false,
//                     "chapterId": 651,
//                     "chapterName": "鸿蒙开发常用链接",
//                     "collect": false,
//                     "courseId": 13,
//                     "desc": "查找各种鸿蒙示例代码。",
//                     "descMd": "",
//                     "envelopePic": "",
//                     "fresh": false,
//                     "host": "",
//                     "id": 28065,
//                     "isAdminAdd": false,
//                     "link": "https://developer.huawei.com/consumer/cn/hmos/samples/?catalogVersion=V2",
//                     "niceDate": "2024-02-25 15:58",
//                     "niceShareDate": "2024-02-25 15:58",
//                     "origin": "",
//                     "prefix": "",
//                     "projectLink": "",
//                     "publishTime": 1708847898000,
//                     "realSuperChapterId": 648,
//                     "selfVisible": 0,
//                     "shareDate": 1708847898000,
//                     "shareUser": "",
//                     "superChapterId": 649,
//                     "superChapterName": "鸿蒙Tab",
//                     "tags": [],
//                     "title": "官方示例代码：HarmonyOS开源示例",
//                     "type": 0,
//                     "userId": -1,
//                     "visible": 0,
//                     "zan": 0
//                 }
//             ],
//             "author": "",
//             "children": [],
//             "courseId": 13,
//             "cover": "",
//             "desc": "",
//             "id": 651,
//             "lisense": "",
//             "lisenseLink": "",
//             "name": "鸿蒙开发常用链接",
//             "order": 320002,
//             "parentChapterId": 648,
//             "type": 0,
//             "userControlSetTop": false,
//             "visible": 1
//         },
//         "open_sources": {
//             "articleList": [
//                 {
//                     "adminAdd": false,
//                     "apkLink": "",
//                     "audit": 1,
//                     "author": "鸿洋",
//                     "canEdit": false,
//                     "chapterId": 650,
//                     "chapterName": "鸿蒙开发必备开源库",
//                     "collect": false,
//                     "courseId": 13,
//                     "desc": "Axios ，是一个基于 promise 的网络请求库，可以运行 node.js 和浏览器中。本库基于Axios 原库v1.3.4版本进行适配，使其可以运行在 OpenHarmony，并沿用其现有用法和特性。\n",
//                     "descMd": "",
//                     "envelopePic": "",
//                     "fresh": false,
//                     "host": "",
//                     "id": 28028,
//                     "isAdminAdd": false,
//                     "link": "https://ohpm.openharmony.cn/#/cn/detail/@ohos%2Faxios",
//                     "niceDate": "2024-02-24 12:05",
//                     "niceShareDate": "2024-02-24 12:05",
//                     "origin": "",
//                     "prefix": "",
//                     "projectLink": "",
//                     "publishTime": 1708747556000,
//                     "realSuperChapterId": 648,
//                     "selfVisible": 0,
//                     "shareDate": 1708747556000,
//                     "shareUser": "",
//                     "superChapterId": 649,
//                     "superChapterName": "鸿蒙Tab",
//                     "tags": [],
//                     "title": "网络库：@ohos/axios",
//                     "type": 0,
//                     "userId": -1,
//                     "visible": 1,
//                     "zan": 0
//                 },
//                 {
//                     "adminAdd": false,
//                     "apkLink": "",
//                     "audit": 1,
//                     "author": "鸿洋",
//                     "canEdit": false,
//                     "chapterId": 650,
//                     "chapterName": "鸿蒙开发必备开源库",
//                     "collect": false,
//                     "courseId": 13,
//                     "desc": "lottie是一个适用于OpenHarmony的动画库，它可以解析Adobe After Effects软件通过Bodymovin插件导出的json格式的动画，并在移动设备上进行本地渲染。",
//                     "descMd": "",
//                     "envelopePic": "",
//                     "fresh": false,
//                     "host": "",
//                     "id": 28029,
//                     "isAdminAdd": false,
//                     "link": "https://ohpm.openharmony.cn/#/cn/detail/@ohos%2Flottie",
//                     "niceDate": "2024-02-24 12:07",
//                     "niceShareDate": "2024-02-24 12:07",
//                     "origin": "",
//                     "prefix": "",
//                     "projectLink": "",
//                     "publishTime": 1708747623000,
//                     "realSuperChapterId": 648,
//                     "selfVisible": 0,
//                     "shareDate": 1708747623000,
//                     "shareUser": "",
//                     "superChapterId": 649,
//                     "superChapterName": "鸿蒙Tab",
//                     "tags": [],
//                     "title": "Lottie 动画库：@ohos/lottie",
//                     "type": 0,
//                     "userId": -1,
//                     "visible": 1,
//                     "zan": 0
//                 },
//                 {
//                     "adminAdd": false,
//                     "apkLink": "",
//                     "audit": 1,
//                     "author": "鸿洋",
//                     "canEdit": false,
//                     "chapterId": 650,
//                     "chapterName": "鸿蒙开发必备开源库",
//                     "collect": false,
//                     "courseId": 13,
//                     "desc": "PullToRefresh是一款OpenHarmony环境下可用的下拉刷新、上拉加载组件。 支持设置内置动画的各种属性，支持设置自定义动画。",
//                     "descMd": "",
//                     "envelopePic": "",
//                     "fresh": false,
//                     "host": "",
//                     "id": 28030,
//                     "isAdminAdd": false,
//                     "link": "https://ohpm.openharmony.cn/#/cn/detail/@ohos%2Fpulltorefresh",
//                     "niceDate": "2024-02-24 12:07",
//                     "niceShareDate": "2024-02-24 12:07",
//                     "origin": "",
//                     "prefix": "",
//                     "projectLink": "",
//                     "publishTime": 1708747659000,
//                     "realSuperChapterId": 648,
//                     "selfVisible": 0,
//                     "shareDate": 1708747659000,
//                     "shareUser": "",
//                     "superChapterId": 649,
//                     "superChapterName": "鸿蒙Tab",
//                     "tags": [],
//                     "title": "下拉刷新库：@ohos/pulltorefresh",
//                     "type": 0,
//                     "userId": -1,
//                     "visible": 1,
//                     "zan": 0
//                 }
//             ],
//             "author": "",
//             "children": [],
//             "courseId": 13,
//             "cover": "",
//             "desc": "",
//             "id": 650,
//             "lisense": "",
//             "lisenseLink": "",
//             "name": "鸿蒙开发必备开源库",
//             "order": 320001,
//             "parentChapterId": 648,
//             "type": 0,
//             "userControlSetTop": false,
//             "visible": 1
//         },
//         "tools": {
//             "articleList": [
//                 {
//                     "adminAdd": false,
//                     "apkLink": "",
//                     "audit": 1,
//                     "author": "鸿洋",
//                     "canEdit": false,
//                     "chapterId": 649,
//                     "chapterName": "鸿蒙开发常用工具",
//                     "collect": false,
//                     "courseId": 13,
//                     "desc": "将 Server 返回的 Json 字符串，一键转成 TS 实体类，粘贴到项目简单修改即可。千万不要手敲...千万不要手敲...千万不要手敲...",
//                     "descMd": "",
//                     "envelopePic": "",
//                     "fresh": false,
//                     "host": "",
//                     "id": 28025,
//                     "isAdminAdd": false,
//                     "link": "https://app.quicktype.io/?l=ts",
//                     "niceDate": "2024-02-24 11:52",
//                     "niceShareDate": "2024-02-24 11:52",
//                     "origin": "",
//                     "prefix": "",
//                     "projectLink": "",
//                     "publishTime": 1708746723000,
//                     "realSuperChapterId": 648,
//                     "selfVisible": 0,
//                     "shareDate": 1708746723000,
//                     "shareUser": "",
//                     "superChapterId": 649,
//                     "superChapterName": "鸿蒙Tab",
//                     "tags": [],
//                     "title": "Json 转 TS",
//                     "type": 0,
//                     "userId": -1,
//                     "visible": 1,
//                     "zan": 0
//                 },
//                 {
//                     "adminAdd": false,
//                     "apkLink": "",
//                     "audit": 1,
//                     "author": "鸿洋",
//                     "canEdit": false,
//                     "chapterId": 649,
//                     "chapterName": "鸿蒙开发常用工具",
//                     "collect": false,
//                     "courseId": 13,
//                     "desc": "beJson - Json 格式化，将 Server 返回的Json 字符串格式化，树形展示。",
//                     "descMd": "",
//                     "envelopePic": "",
//                     "fresh": false,
//                     "host": "",
//                     "id": 28039,
//                     "isAdminAdd": false,
//                     "link": "https://www.wanandroid.com/tools/bejson",
//                     "niceDate": "2024-02-24 21:03",
//                     "niceShareDate": "2024-02-24 21:03",
//                     "origin": "",
//                     "prefix": "",
//                     "projectLink": "",
//                     "publishTime": 1708779834000,
//                     "realSuperChapterId": 648,
//                     "selfVisible": 0,
//                     "shareDate": 1708779834000,
//                     "shareUser": "",
//                     "superChapterId": 649,
//                     "superChapterName": "鸿蒙Tab",
//                     "tags": [],
//                     "title": "beJson - Json 格式化",
//                     "type": 0,
//                     "userId": -1,
//                     "visible": 1,
//                     "zan": 0
//                 },
//                 {
//                     "adminAdd": false,
//                     "apkLink": "",
//                     "audit": 1,
//                     "author": "鸿洋",
//                     "canEdit": false,
//                     "chapterId": 649,
//                     "chapterName": "鸿蒙开发常用工具",
//                     "collect": false,
//                     "courseId": 13,
//                     "desc": "MD5，SHA1，SHA224，SHA256，SHA384，SHA512在线加密，计算摘要。",
//                     "descMd": "",
//                     "envelopePic": "",
//                     "fresh": false,
//                     "host": "",
//                     "id": 28040,
//                     "isAdminAdd": false,
//                     "link": "https://www.wanandroid.com/tools/digit",
//                     "niceDate": "2024-02-24 21:05",
//                     "niceShareDate": "2024-02-24 21:05",
//                     "origin": "",
//                     "prefix": "",
//                     "projectLink": "",
//                     "publishTime": 1708779904000,
//                     "realSuperChapterId": 648,
//                     "selfVisible": 0,
//                     "shareDate": 1708779904000,
//                     "shareUser": "",
//                     "superChapterId": 649,
//                     "superChapterName": "鸿蒙Tab",
//                     "tags": [],
//                     "title": "MD5，SHA等加密算法",
//                     "type": 0,
//                     "userId": -1,
//                     "visible": 1,
//                     "zan": 0
//                 },
//                 {
//                     "adminAdd": false,
//                     "apkLink": "",
//                     "audit": 1,
//                     "author": "鸿洋",
//                     "canEdit": false,
//                     "chapterId": 649,
//                     "chapterName": "鸿蒙开发常用工具",
//                     "collect": false,
//                     "courseId": 13,
//                     "desc": "支持将字符串encode为base64，也支持将base64 decode为原字符串。\n",
//                     "descMd": "",
//                     "envelopePic": "",
//                     "fresh": false,
//                     "host": "",
//                     "id": 28042,
//                     "isAdminAdd": false,
//                     "link": "https://www.wanandroid.com/tools/base64",
//                     "niceDate": "2024-02-24 21:06",
//                     "niceShareDate": "2024-02-24 21:06",
//                     "origin": "",
//                     "prefix": "",
//                     "projectLink": "",
//                     "publishTime": 1708779982000,
//                     "realSuperChapterId": 648,
//                     "selfVisible": 0,
//                     "shareDate": 1708779982000,
//                     "shareUser": "",
//                     "superChapterId": 649,
//                     "superChapterName": "鸿蒙Tab",
//                     "tags": [],
//                     "title": "Base64 - 字符串互转",
//                     "type": 0,
//                     "userId": -1,
//                     "visible": 1,
//                     "zan": 0
//                 },
//                 {
//                     "adminAdd": false,
//                     "apkLink": "",
//                     "audit": 1,
//                     "author": "鸿洋",
//                     "canEdit": false,
//                     "chapterId": 649,
//                     "chapterName": "鸿蒙开发常用工具",
//                     "collect": false,
//                     "courseId": 13,
//                     "desc": "将复杂的url在线进行 decode，也可以将参数encode。",
//                     "descMd": "",
//                     "envelopePic": "",
//                     "fresh": false,
//                     "host": "",
//                     "id": 28043,
//                     "isAdminAdd": false,
//                     "link": "https://www.wanandroid.com/tools/decode",
//                     "niceDate": "2024-02-24 21:07",
//                     "niceShareDate": "2024-02-24 21:07",
//                     "origin": "",
//                     "prefix": "",
//                     "projectLink": "",
//                     "publishTime": 1708780047000,
//                     "realSuperChapterId": 648,
//                     "selfVisible": 0,
//                     "shareDate": 1708780047000,
//                     "shareUser": "",
//                     "superChapterId": 649,
//                     "superChapterName": "鸿蒙Tab",
//                     "tags": [],
//                     "title": "URL decode、encode",
//                     "type": 0,
//                     "userId": -1,
//                     "visible": 1,
//                     "zan": 0
//                 },
//                 {
//                     "adminAdd": false,
//                     "apkLink": "",
//                     "audit": 1,
//                     "author": "鸿洋",
//                     "canEdit": false,
//                     "chapterId": 649,
//                     "chapterName": "鸿蒙开发常用工具",
//                     "collect": false,
//                     "courseId": 13,
//                     "desc": "在线二维码制作，可以将链接一键转为二维码进行分享。",
//                     "descMd": "",
//                     "envelopePic": "",
//                     "fresh": false,
//                     "host": "",
//                     "id": 28044,
//                     "isAdminAdd": false,
//                     "link": "https://www.wanandroid.com/tools/qrcode",
//                     "niceDate": "2024-02-24 21:08",
//                     "niceShareDate": "2024-02-24 21:08",
//                     "origin": "",
//                     "prefix": "",
//                     "projectLink": "",
//                     "publishTime": 1708780096000,
//                     "realSuperChapterId": 648,
//                     "selfVisible": 0,
//                     "shareDate": 1708780096000,
//                     "shareUser": "",
//                     "superChapterId": 649,
//                     "superChapterName": "鸿蒙Tab",
//                     "tags": [],
//                     "title": "在线二维码制作 - 字符串一键转",
//                     "type": 0,
//                     "userId": -1,
//                     "visible": 1,
//                     "zan": 0
//                 },
//                 {
//                     "adminAdd": false,
//                     "apkLink": "",
//                     "audit": 1,
//                     "author": "鸿洋",
//                     "canEdit": false,
//                     "chapterId": 649,
//                     "chapterName": "鸿蒙开发常用工具",
//                     "collect": false,
//                     "courseId": 13,
//                     "desc": "支持各类进制相互转化，支持整形数字转换，",
//                     "descMd": "",
//                     "envelopePic": "",
//                     "fresh": false,
//                     "host": "",
//                     "id": 28045,
//                     "isAdminAdd": false,
//                     "link": "https://www.wanandroid.com/tools/decimal",
//                     "niceDate": "2024-02-24 21:09",
//                     "niceShareDate": "2024-02-24 21:09",
//                     "origin": "",
//                     "prefix": "",
//                     "projectLink": "",
//                     "publishTime": 1708780144000,
//                     "realSuperChapterId": 648,
//                     "selfVisible": 0,
//                     "shareDate": 1708780144000,
//                     "shareUser": "",
//                     "superChapterId": 649,
//                     "superChapterName": "鸿蒙Tab",
//                     "tags": [],
//                     "title": "进制转化：2进制、8进制、16 进制、32 进制",
//                     "type": 0,
//                     "userId": -1,
//                     "visible": 1,
//                     "zan": 0
//                 }
//             ],
//             "author": "",
//             "children": [],
//             "courseId": 13,
//             "cover": "",
//             "desc": "",
//             "id": 649,
//             "lisense": "",
//             "lisenseLink": "",
//             "name": "鸿蒙开发常用工具",
//             "order": 320000,
//             "parentChapterId": 648,
//             "type": 0,
//             "userControlSetTop": false,
//             "visible": 1
//         }
//     }
//上面对应的数据，生成数据实体
class HarmonyosColumn {
  HarmonyosColumnLinks links;
  HarmonyosColumnOpenSources open_sources;
  HarmonyosColumnTools tools;

  // 构造函数
  HarmonyosColumn({required this.links, required this.open_sources, required this.tools});

  //工厂模式
  factory HarmonyosColumn.fromJson(Map<String, dynamic> json) {
    return HarmonyosColumn(
      links: HarmonyosColumnLinks.fromJson(json['links']),
      open_sources: HarmonyosColumnOpenSources.fromJson(json['open_sources']),
      tools: HarmonyosColumnTools.fromJson(json['tools']),
    );
  }
}

class HarmonyosColumnLinks {
  int id;
  String name;
  String link;
  List<HarmonyosColumnArticle> articleList = [];
  // 构造函数
  HarmonyosColumnLinks({required this.id, required this.name, required this.link, required this.articleList});

  // 工厂模式
  factory HarmonyosColumnLinks.fromJson(Map<String, dynamic> json) {
    return HarmonyosColumnLinks(
      id: json['id'] ?? 0,
      name: json['name'] ?? '',
      link: json['link'] ?? '',
      articleList: (json['articleList'] as List).map((e) => HarmonyosColumnArticle.fromJson(e as Map<String, dynamic>)).toList(),
    );
  }
}

class HarmonyosColumnArticle {
  int audit;
  String author;
  String chapterName;
  String desc;
  String superChapterName;
  String niceDate;
  String link;
  // 构造函数
  HarmonyosColumnArticle({
    required this.audit,
    required this.author,
    required this.chapterName,
    required this.desc,
    required this.superChapterName,
    required this.niceDate,
    required this.link,
  });

  // 工厂模式
  factory HarmonyosColumnArticle.fromJson(Map<String, dynamic> json) {
    return HarmonyosColumnArticle(
      audit: json['audit'] ?? 0,
      author: json['author'] ?? '',
      chapterName: json['chapterName'] ?? '',
      desc: json['desc'] ?? '',
      superChapterName: json['superChapterName'] ?? '',
      niceDate: json['niceDate'] ?? '',
      link: json['link'] ?? '',
    );
  }
}

class HarmonyosColumnOpenSources {
  int id;
  String name;
  List<HarmonyosColumnArticle> articleList = [];
  // 构造函数
  HarmonyosColumnOpenSources({required this.id, required this.name, required this.articleList});

  // 工厂模式
  factory HarmonyosColumnOpenSources.fromJson(Map<String, dynamic> json) {
    return HarmonyosColumnOpenSources(
      id: json['id'] ?? 0,
      name: json['name'] ?? '',
      articleList: (json['articleList'] as List).map((e) => HarmonyosColumnArticle.fromJson(e as Map<String, dynamic>)).toList(),
    );
  }
}

class HarmonyosColumnTools {
  int id;
  String name;
  List<HarmonyosColumnArticle> articleList = [];
  // 构造函数
  HarmonyosColumnTools({required this.id, required this.name, required this.articleList});

  // 工厂模式
  factory HarmonyosColumnTools.fromJson(Map<String, dynamic> json) {
    return HarmonyosColumnTools(
      id: json['id'] ?? 0,
      name: json['name'] ?? '',
      articleList: (json['articleList'] as List).map((e) => HarmonyosColumnArticle.fromJson(e as Map<String, dynamic>)).toList(),
    );
  }
}
